### ISSUE TITLE
需要多少显存

### ISSUE THREAD

**Issue by huangsusan** [MedICL-VU/ProMISe#4]
您好：
我运行了您的代码，发现在24G显存上跑不起来，请问大概需要多少显存呢

**Comment by HaoLi12345** [comment]
I'm so sorry for the delayed response. GitHub doesn't send me notifications about issues. The process requires around 42GB of memory. To reduce memory consumption, you can avoid upsampling the image for the ViT encoder, but this may decrease accuracy.

**Comment by ax130885** [comment]
您好，感謝您出色的貢獻。
我嘗試使用您提供的預訓練模型，來推論本地的資料，即可得到很好的結果。
但當我想嘗試訓練時，我也遇到 GPU 記憶體不足的問題 (我使用RTX3090 24G)。

我嘗試降低模型的大小來解決（我不知道這樣做是否合理）。
但當我修改config_setup.py中img_encoder()的參數時，
會產生模型尺寸錯誤的error。
```python
    img_encoder = Promise(
        depth=12,
        embed_dim=192,
        img_size=256,
        mlp_ratio=4,
        norm_layer=partial(torch.nn.LayerNorm, eps=1e-6),
        num_heads=12,
        patch_size=4,
        qkv_bias=True,
        use_rel_pos=True,
        global_attn_indexes=[2, 5, 8, 11],
        window_size=14,
        cubic_window_size=8,
        out_chans=256,
        num_slice=16)
```

```bash
(promise) [yuxin@jujube promise]$ CUDA_VISIBLE_DEVICES=3 python src/train.py --data colon --data_dir dataset/Task10_Colon --save_dir to_save_model_and_log --max_epoch 20 --num_worker 4 --batch_size 1
/home/graduate/yuxin/ProMISe_main/promise/src/config/config_args.py:50: UserWarning: [save_name] (--save_name) should be a real name, currently is for testing purpose (--save_name=testing_only)
  warnings.warn("[save_name] (--save_name) should be a real name, currently is for testing purpose (--save_name=testing_only)")
[07:13:00.001] Namespace(data='colon', save_dir='to_save_model_and_log/colon/testing_only', data_dir='dataset/Task10_Colon', num_worker=4, split='train', lr=0.0004, device='cuda:0', max_epoch=20, batch_size=1, rand_crop_size=(128, 128, 128), checkpoint='best', checkpoint_sam='./checkpoint_sam/sam_vit_b_01ec64.pth', num_prompts=1, num_classes=2, tolerance=5, boundary_kernel_size=5, use_pretrain=False, pretrain_path='', save_predictions=False, save_csv=False, save_base_dir='colon/testing_only', save_name='testing_only')
2024-08-02 07:13:00,001 - Namespace(data='colon', save_dir='to_save_model_and_log/colon/testing_only', data_dir='dataset/Task10_Colon', num_worker=4, split='train', lr=0.0004, device='cuda:0', max_epoch=20, batch_size=1, rand_crop_size=(128, 128, 128), checkpoint='best', checkpoint_sam='./checkpoint_sam/sam_vit_b_01ec64.pth', num_prompts=1, num_classes=2, tolerance=5, boundary_kernel_size=5, use_pretrain=False, pretrain_path='', save_predictions=False, save_csv=False, save_base_dir='colon/testing_only', save_name='testing_only')
loading models and setting up
Traceback (most recent call last):
  File "/home/graduate/yuxin/ProMISe_main/promise/src/train.py", line 23, in <module>
    main()
  File "/home/graduate/yuxin/ProMISe_main/promise/src/train.py", line 19, in main
    Trainer(args, logger).run()
  File "/home/graduate/yuxin/ProMISe_main/promise/src/processor/trainer.py", line 23, in __init__
    self.model_dict, self.parameter_list = load_model(args, logger)
  File "/home/graduate/yuxin/ProMISe_main/promise/src/config/config_setup.py", line 138, in load_model
    img_encoder.load_state_dict(mask_generator.predictor.model.image_encoder.state_dict(), strict=False)
  File "/home/graduate/yuxin/anaconda3/envs/promise/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1604, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Promise:
        size mismatch for pos_embed: copying a param with shape torch.Size([1, 64, 64, 768]) from checkpoint, the shape in current model is torch.Size([1, 64, 64, 192]).
        size mismatch for patch_embed.proj.weight: copying a param with shape torch.Size([768, 3, 16, 16]) from checkpoint, the shape in current model is torch.Size([192, 3, 4, 4]).
        size mismatch for patch_embed.proj.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([192]).
        size mismatch for blocks.0.norm1.weight: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([192]).
        size mismatch for blocks.0.norm1.bias: copying a param with shape torch.Size([768]) from checkpoint, the shape in current model is torch.Size([192]).
        size mismatch for blocks.0.attn.rel_pos_h: copying a param with shape torch.Size([27, 64]) from checkpoint, the shape in current model is torch.Size([27, 16]).
        size mismatch for blocks.0.attn.rel_pos_w: copying a param with shape torch.Size([27, 64]) from checkpoint, the shape in current model is torch.Size([27, 16]).
```

我想請問: 
1.您在前一個回答當中提到 "you can avoid upsampling the image for the ViT encoder" 是指我正在修改中的部份嗎?
2.我該怎麼修改這些參數比較合理呢?
3.前幾天meta剛發布了SAM2，我可以直接將其新提供的預訓練模型檔，替換掉sam_vit_b_01ec64.pth嗎?

**Comment by HaoLi12345** [comment]
Hello,

Oh, sorry for the unclear explanations.

The error is about mismatched size, i.e. 768 and 192 for pos_embed which is a nn.parameter().

If you use pertained model, the size should be the same as I used and it takes around 42G. If you train from scratch, you can reduce the input and model sizes. if you want to test colon dataset, you can use PRISM (https://arxiv.org/pdf/2404.15028), which takes around 24G.

Yes, I have also noticed the SAM2, an amazing work. They also use ViT as image encoder and it can be adapted to this work. This work can take other retrained ViT as well.

Hope these help!

Hao

**Comment by ax130885** [comment]
感謝您的回覆:

> If you use pertained model, the size should be the same as I used and it takes around 42G.

想請問您提到的 pretrained model，是指 sam_vit_b_01ec64.pth 還是 colon_pretrain_promise.pth.tar 呢?
我的理解是，我輸入的訓練指令，當中沒有使用 --use_pretrain 和 --pretrain_path。
所以沒有用到 colon_pretrain_promise.pth.tar (包含cnn encoder、mask decoder、prompt encoder)，
但有用到sam_vit_b_01ec64.pth (image encoder)。
因此如果我更換不同的 image encoder，就需要調整config_setup.py內的所有參數，使其相配新的image encoder。
請問我的想法正確嗎?

另外我也會嘗試看看PRISM，謝謝您的建議。

**Comment by HaoLi12345** [comment]
it is for colon_pretrain_promise.pth.tar.

if you only use SAM' ViT, you can use any image size as long as it can be divided by 16. Please remember to change the size of pos_embed and other variables.

I remember SAM uses self-supervised learning for pretrain and use 1024x1024 to fit the pretrained model with self-supervised learning. For inference, they upsample/resize the input image if you use a smaller size input image. So, for a pretrained SAM like sam_vit_b_01ec64.pth, I guess an input size closer to SAM's original image size would yield more accurate outcomes.

Yes, your thought is correct. You need to set another configuration based on your dataset.

:)
Hao
